name: Deploy on staging
on: 
    push:
        branches: [main]

jobs:
    redeploy_everything:
        runs-on: ubuntu-latest
        name: Deploying everything to the staging cluster
        
        steps:
            - name: SSH into Server and Deploy
              run: |
                # Setup SSH key
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
                chmod 600 ~/ssh_key
                
                # Setup known_hosts
                mkdir -p ~/.ssh
                echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
                chmod 644 ~/.ssh/known_hosts
                
                # SSH and run commands on remote server
                ssh -i ~/ssh_key -o StrictHostKeyChecking=no ubuntu@16.16.126.130 << 'EOF'
                  cd ~/bms/
                  git pull origin main
                  pnpm install
                  pnpm run build
                  pm2 restart http-server
                  pm2 restart web
                  pm2 restart ws-server
                EOF