name: Deply on staging
on: 
    push:
        branches:
            -"main"

jobs:
    redeploy_everything:
        name: Deployinig everything to the staging cluster
        runs-on: ubuntu-latest
        
        steps:
            - name: SSH into Server
              run: |
                echo ${{ secrets.SSH_PRIVATE_KEY }} &> ~/ssh_key
                chmod 600 ~/ssh_key
                ssh -i ~/ssh_key ubuntu@16.16.126.130 << 'EOF'
                cd bms/ && git pull
                pnpm install
                pnpm run build
                pm2 restart http-server
                pm2 restart web
                pm2 restart ws-server
                EOF

             