name: Deploy on staging
on: 
    push:
        branches: [main]

jobs:
    redeploy_everything:
        runs-on: ubuntu-latest
        name: Deploying everything to the staging cluster
        
        steps:
            - name: SSH into Server and Deploy
              run: |
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
                chmod 600 ~/ssh_key
                
                ssh -i ~/ssh_key -o StrictHostKeyChecking=no ubuntu@16.16.126.130 << 'EOF'
                export PATH=$HOME/.local/share/pnpm:$PATH
                export NVM_DIR="$HOME/.nvm"
                [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                
                cd ~/bms/
                git pull origin main
                pnpm install
                pnpm run build
                pm2 restart http-server
                pm2 restart web
                pm2 restart ws-server
                EOF